src/main/groovy/groovyx/grooid/GroovyAndroidPlugin.groovy
I was trying to make Spock tests for a "normal" Java Android project, something that I think might be of great interest for much people. I realized that it wasn't possible yet to do it in the same module where the code is, although it's something possible in the Android gradle plugin since version 1.1.0. This change seems to be working fine for me, unit tests are executed correctly and Android Studio recognizes "src/test/groovy" as a valid source code directory.
=> Support for Android plugin 1.1 unit tests

src/main/groovy/groovyx/grooid/GroovyAndroidPlugin.groovy
Compile task names are called compileJava**WithJavac** since android plugin 1.3.0. Method replaceFirst is used to transform task "compileJavaWithJavac" to "compileUnitTestJavaWithJavac" but not to "compileUnitTestJavaWithUnitTestJavac".
=> Support for android plugin 1.3.0

README.md
I use the guild in the Readme, and failed the build
```groovy
repository {
jcenter()
}
```
it actually should be 
```grooovy
repositories {
jcenter()
}
``
=> fix a misguide in Readme.md

src/main/groovy/groovyx/grooid/GroovyAndroidPlugin.groovy
- Added new signature of AndroidBuilder.getBootClasspath(boolean)
- Added RegEx to match version 1.4.0-beta1, 1.4.0-beta2
=> Added support for com.android.tools.build:gradle:1.4.0-beta2

src/main/groovy/groovyx/grooid/GroovyAndroidPlugin.groovy, src/test/groovy/groovyx/grooid/GroovyAndroidPluginTest.groovy, src/test/groovy/groovyx/grooid/TestableGroovyAndroidPlugin.groovy
- Fixed getRuntimeJars, to return correct runtimeJars for version 1.2.x and 1.3.x (broken in previous commit)
- Simple refactorings to GroovyAndroidPlugin, to facilitate testing:
1. new method getRuntimeJarsIndex(pluginVersion), refactored from getRuntimeJars(project, plugin)
2. getRuntimeJars(project, plugin) to getRuntimeJars(pluginVersion, plugin)
- Added GroovyAndroidPluginTest to ensure that all supported versions of the build plugin are getting the correct runtime jars
=> Fix to previous commit, that broke runtimeJars to versions 1.2.x and 1.3.x

README.md
Hi, I would like to add a mention about `packagingOptions' related to extension modules and global transformations. Also want to add a mention to the emerger plugin.
BTW I'm not 100% about the following statement: "Unless you statically
compile classes using extension modules with @CompileStatic they won't
be available at runtime" 
I know that by experience, but it would be nice if 
@Cedric could confirm I'm not wrong.
=> Add packagingOptions mention and emerger plugin mention

gradle-groovy-android-plugin/src/main/groovy/groovyx/grooid/GroovyAndroidPlugin.groovy
Update Groovy compilation task's classpath first, to use the latest classpath which may be updated by other tasks.
This assume groovyCompile execute after javaCompile.
=> update Groovy compilation task's classpath first when execute it

groovy-android-sample-app/sample-app.gradle
project.androidGroovy block from "Configuring the Groovy compilation options" was added to sample's application .gradle file
=> Added project.androidGroovy block to example application's gradle file

.travis.yml, build.gradle, gradle-groovy-android-plugin/gradle-plugin.gradle, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/functional/FullCompilationSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/functional/FunctionalSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/internal/TestProperties.groovy, gradle/androidGroovyLocal.gradle, groovy-android-sample-app/sample-app.gradle
Check will only run a small subset of functional tests so that features can be
easier implemented rather than waiting 6 minutes for all functional tests on
each android version to run.
Now only the latest version of android and gradle are used for standard checks
and fullTest will run a variety of tests.
=> check task will only run small subset of functional tests

CHANGELOG.md, README.md, gradle-groovy-android-plugin/src/main/groovy/groovyx/grooid/GroovyAndroidExtension.groovy, gradle-groovy-android-plugin/src/main/groovy/groovyx/grooid/GroovyAndroidPlugin.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/GroovyAndroidExtensionSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/GroovyAndroidPluginSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/functional/FullCompilationSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/functional/RenderScriptCompilationSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/functional/SkipJavaCSpec.groovy
A flag was added to the plugin `androidGroovy.skipJavaC` that when
set to true will exclude all sources in the JavaCompile task
and will add them to the GroovyCompile task.
=> Ability for GroovyC Compile all Source

gradle-groovy-android-plugin/src/main/groovy/groovyx/grooid/GroovyAndroidPlugin.groovy
This fixes an issue where the groovy sources were not being applied correctly to the java
sources, causing these folders to not show up as source folders automatically by Android Studio.
=> Update GroovyAndroidPlugin Java Sources

build.gradle, gradle-groovy-android-plugin/gradle-plugin.gradle, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/GroovyAndroidExtensionSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/GroovyAndroidPluginSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/functional/CompilationSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/functional/FullCompilationSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/functional/RenderScriptCompilationSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/functional/SkipJavaCSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/functional/SourceSetSpec.groovy, gradle-groovy-android-plugin/src/test/groovy/groovyx/grooid/internal/TestProperties.groovy, groovy-android-sample-app/sample-app.gradle
Tests all use the same build tools version, compileSdk version,
and android plugin version.
=> Updated Tests

build.gradle, groovy-android-gradle-plugin/src/test/groovy/groovyx/functional/CompilationSpec.groovy
- Updated Compilation Spec Text. No JavaVersion
or Gradle Version supplied for printing out.
- Updated build.gradle to use the path of the 1.0.0 plugin.
This was being overriden by buildSrc, but when you want to
comment this out for intellij this is nice.
=> Minor Text Changes

CHANGELOG.md, build.gradle, groovy-android-gradle-plugin/gradle-plugin.gradle, groovy-android-gradle-plugin/src/main/groovy/groovyx/GroovyAndroidPlugin.groovy, groovy-android-gradle-plugin/src/test/groovy/groovyx/functional/FullCompilationSpec.groovy
This removes the need to update the plugin with new dependencies as they come out
or have the users remove the dependent plugin and add the version they want for
their version.
#127
=> Removed direct dependency on Android Gradle Plugin

groovy-android-gradle-plugin/src/test/groovy/groovyx/GroovyAndroidExtensionSpec.groovy
Fixed test checking source directories on Windows by replacing backslashes with slashes.
=> Fixed test checking source directories on windows

.travis.yml, build.gradle, groovy-android-gradle-plugin/src/main/groovy/groovyx/GroovyAndroidPlugin.groovy, groovy-android-gradle-plugin/src/test/groovy/groovyx/GroovyAndroidPluginSpec.groovy, groovy-android-gradle-plugin/src/test/groovy/groovyx/functional/FullCompilationSpec.groovy, groovy-android-gradle-plugin/src/test/groovy/groovyx/internal/AndroidPluginHelper.groovy, groovy-android-sample-app/sample-app.gradle
Source sets with no groovy sources are are skipped by default
this should speed up builds and allow groovy to only be used
for tests while Java and/or Kotlin are in the main source set.
relates to #119 and #139
=> Disable Groovy Task when No Sources

build.gradle, gradle/wrapper/gradle-wrapper.properties, groovy-android-gradle-plugin/src/main/groovy/groovyx/internal/DefaultAndroidGroovySourceSet.groovy, groovy-android-gradle-plugin/src/test/groovy/groovyx/functional/FullCompilationSpec.groovy
Updated to Gradle 3.5 from 2.14. Updated tests to include Gradle 3.5.
Fixed breaking change from Gradle 3.2 to 3.3 where the GroovySourceSet
interface had a method added to it.
=> Updated to Gradle 3.5

README.adoc, RELEASE.adoc, RELEASE.md
README:
- added info on skipping groovy compile tasks (#144)
- updated android Gradle plugin version and groovy library version
RELEASE:
- Converted to asciidoc
=> Updated Docs

CHANGELOG.md, build.gradle, groovy-android-gradle-plugin/gradle-plugin.gradle, groovy-android-gradle-plugin/src/main/groovy/groovyx/GroovyAndroidPlugin.groovy, groovy-android-gradle-plugin/src/test/groovy/groovyx/GroovyAndroidPluginSpec.groovy, groovy-android-gradle-plugin/src/test/groovy/groovyx/functional/KotlinSupportSpec.groovy
You can now intermix Java, Kotlin, and Groovy files all in the same
project. This pull request adds compiled Kotlin class files to
GroovyCompile's classpath allowing these classes to be referenced
inside of Groovy files.
Fixes: #139
=> Allow Groovy to compile with Kotlin references

groovy-android-gradle-plugin/src/main/groovy/groovyx/GroovyAndroidPlugin.groovy, groovy-android-gradle-plugin/src/test/groovy/groovyx/GroovyAndroidPluginSpec.groovy, groovy-android-gradle-plugin/src/test/groovy/groovyx/internal/AndroidFileHelper.groovy
The original way this was implemented it not prevent the task from
running. Now if there are no sources the task is removed and
the should be skipped properly.
=> Updated Compilation Tasks Requirements

build.gradle, gradle.properties
4.4.12 seems to work, 4.5.0 not so much.
=> Revert build-info-extractor-gradle
